### PR TITLE
Shrink .PNG filesizes

### PR DESCRIPTION
**Pull request by TPS**
@92lleo This shrinks all the images' filesizes losslessly via [ImgBot](https://ImgBot.net), which is free to subscribe for FOSS.

### CODE REVIEW

**Comment by 92lleo** [comment]
Hi @TPS,
thanks for this PR! The images are mainly screenshots for store entries. Nevertheless a good idea. I guess ImgBot acts on every commit and optimizes new images automatically?

**Comment by TPS** [comment]
@92lleo Exactly that, down to a minimal threshold of savings, & then will put in a PR for the changes.  & don't knock the store images: if they're the same 1s used for F-droid, that's quite helpful for the end user, as well.

**Comment by 92lleo** [comment]
@TPS okay, perfect. Can you please remove the commit by imagebot (should create the first PR automatically then?) and squash the addition of .imgbot to one commit?

**Comment by TPS** [comment]
I actually have to remove the entire ImgBot _branch_ from my fork to get the PR recreated (I believe, from my experience), so I might just scrap this PR & redo, to get that done.

Or, you might just subscribe to ImgBot & have it done directly.

**Comment by 92lleo** [comment]
To update the PR you can just edit your master. 
In case you care:

- The PR is opened to 92lleo:master from TPS:master -> as long as the PR is open, any addition to TPS:master will be shown in this PR. 
- So to change it, you can [interactively rebase](https://stackoverflow.com/a/24527934) your master, remove the commit from imgbot and keep only one of the .imgbot additions. 
- Then force push to your master -> PR is ready

In case you don't:

- I can just do that myself and push the changes, this would result in the git contributing flow being broken (I'd like to keep that). If you don't, we can just close it and I'll add it

In any case: 
- In case of questions feel free to ask
- Thanks for the addition :)

**Comment by TPS** [comment]
Replaced by #37.

**Pull request closed without merging**
