### PR TITLE
improving the ui - ux

### PR DESCRIPTION
**Pull request by andresma2490**

### CODE REVIEW

**Comment by 92lleo** [comment]
Hi @andresma2490 , thanks for your PR!
I'll check any try it in the upcomeing weeks and include it in the next release

**Comment by 92lleo** [comment]
@andresma2490 I'll check it next week. Can you shortly describe your changes in the meantime?

**Comment by andresma2490** [comment]
@92lleo sure, basically I used JavaScript to make the UI clickable

**Comment by 92lleo** [comment]
Just tested it, really nice work!
some additions:

- what javascript command do i need to 
call to "press" the back button when in chat view? I'd like to link it to the phones back button
- the chat overview is really small on my device despite the black space on the right. Can you also span it over the whole screen? (pic 1)
- Screenshot_2022-10-04-20-46-20-73_e2ac8a971e2afc96f6e5bf9327b00845
- when opening a chat for the first time the view is moved to the top a bit, fixed when the size is changed (pic 2)
Screenshot_2022-10-04-20-45-29-27_e2ac8a971e2afc96f6e5bf9327b00845

**Review by Takebackeverythingthatwehavelost — APPROVED** [review]

**Pull request closed without merging**
